executable: "youtube-dl"
supported_version: 
    year:     "2014"
    month:    "09"
    day:      "29"
    release:  "02"
executable_options:
    verbose:            0
    embed-thumbnail:    1
    audio-format:       "mp3"
    audio-quality:      7
    write-info-json:    1
tmpdir: "/tmp"
audio_directory: "mp3"
video_directory: "mp4"
