executable: "youtube-dl"
supported_version: 
    year:     "2014"
    month:    "09"
    day:      "29"
    release:  "02"
executable_options:
    embed-thumbnail:    ON
    audio-format:       "mp3"
    audio-quality:      7
    write-info-json:    ON
    simulate:           Off
    extract-audio:      ON
tmpdir: "/tmp"
audio_directory: "mp3"
video_directory: "mp4"
download_filename: "./t/test_download.yml"
