executable: "youtube-dl"
supported_version: 
    year:     "2014"
    month:    "09"
    day:      "29"
    release:  "02"
# global executable options
executable_options:
    audio-quality:      7
    write-info-json:    ON
    simulate:           ON
    # we handle embed-thumbnail via eyeD3, not default atomicparsley
    embed-thumbnail:    Off
# organization purposes
audio_directory: "mp3"
video_directory: "mp4"
# TODO any tags that I have a rule for,
# will have an auto-tagging attempt
# as long as they are undefined
# example: qr/(?<artist>[^-]+-)/
autotagging: ON 
# overriden in the YoutubeDL::Wrapper
download_filename: "./t/test_download.yml"
max_jobs: 4
# avoiding captcha limiting?
proxy_pool:
    - "" # use my plain connection
    - "http://000111.unblock4ever.info/"
